// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhsqY6Yp2cgXUwx4vCpKnjn5WI3mNc6pU',
    appId: '1:341035987834:web:bb5724db49f0a4f4f15cc3',
    messagingSenderId: '341035987834',
    projectId: 'collegecommute-60a67',
    authDomain: 'collegecommute-60a67.firebaseapp.com',
    databaseURL: 'https://collegecommute-60a67-default-rtdb.firebaseio.com',
    storageBucket: 'collegecommute-60a67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIU_HNAZqabsvTEuXrgzYEfl8YwVdmTo',
    appId: '1:341035987834:android:4fd9070b28f057c5f15cc3',
    messagingSenderId: '341035987834',
    projectId: 'collegecommute-60a67',
    databaseURL: 'https://collegecommute-60a67-default-rtdb.firebaseio.com',
    storageBucket: 'collegecommute-60a67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gtKHkaAHUn4C2cuUi9WXNKwlASEivwk',
    appId: '1:341035987834:ios:fe49a047dcbdf53af15cc3',
    messagingSenderId: '341035987834',
    projectId: 'collegecommute-60a67',
    databaseURL: 'https://collegecommute-60a67-default-rtdb.firebaseio.com',
    storageBucket: 'collegecommute-60a67.firebasestorage.app',
    iosBundleId: 'collegebusroute.collegecommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2gtKHkaAHUn4C2cuUi9WXNKwlASEivwk',
    appId: '1:341035987834:ios:fe49a047dcbdf53af15cc3',
    messagingSenderId: '341035987834',
    projectId: 'collegecommute-60a67',
    databaseURL: 'https://collegecommute-60a67-default-rtdb.firebaseio.com',
    storageBucket: 'collegecommute-60a67.firebasestorage.app',
    iosBundleId: 'collegebusroute.collegecommute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhsqY6Yp2cgXUwx4vCpKnjn5WI3mNc6pU',
    appId: '1:341035987834:web:205b7ef74ca0526bf15cc3',
    messagingSenderId: '341035987834',
    projectId: 'collegecommute-60a67',
    authDomain: 'collegecommute-60a67.firebaseapp.com',
    databaseURL: 'https://collegecommute-60a67-default-rtdb.firebaseio.com',
    storageBucket: 'collegecommute-60a67.firebasestorage.app',
  );

}